version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: monthly
    labels:
      - dependencies
      - python

  - package-ecosystem: npm
    directory: /frontend/rag-app
    schedule:
      interval: monthly
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /frontend/rag-app
    schedule:
      interval: monthly
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
