
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/ethanvillalovoz/acme10-he-ragapp-backend:latest
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}

  frontend:
    build:
      context: ./frontend/rag-app
      dockerfile: dockerfile
    image: ghcr.io/ethanvillalovoz/acme10-he-ragapp-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
